apiVersion: v1
kind: Service
metadata:
  name: gestao-pedidos-db-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 5432
      targetPort: 5432
    - name: https
      protocol: TCP
      port: 443
      targetPort: 5432
  selector:
    app: postgres
#    app: gestao-pedidos-db
  type: LoadBalancer


    