apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gestao-pedidos-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gestao-pedidos-deployment
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 60  