version: '3.7'

services:
    postgres-data:
        image: postgres:alpine
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=docker
        ports:
            - '5432:5432'
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
            - ./postgres/table_atualizada.sql:/docker-entrypoint-initdb.d/table_atualizada.sql
    
#    gestao-pedido-service:
#        image: gestao-pedido-service:${TAG:-latest}
#        environment:
#            - ASPNETCORE_ENVIRONMENT=Development
#        ports:
#            - '80:8080'
#        build:
#            context: .
#            dockerfile: GestaoPedidos.Web/Dockerfile
#        depends_on:
#            - postgres-data
